apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pgc1-backup
  namespace: postgres
spec:
  cluster:
    name: pgc1
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
