apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  labels:
    cnpg.io/reload: "true"
    cnpg.io/userType: "superuser"
  name: pgc1-superuser
  namespace: postgres
stringData:
  username: "postgres"
  password: "{{ DB_SUPERUSER_PASSWORD }}"
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  labels:
    cnpg.io/reload: "true"
  name: dbcreds
  namespace: postgres
stringData:
  username: "cw"
  password: "{{ DB_SUPERUSER_PASSWORD }}"
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  name: blobstorage
  namespace: cnpg-system
stringData:
  ACCESS_KEY_ID: "{{ BLOB_ACCESS_KEY_ID }}"
  ACCESS_SECRET_KEY: "{{ BLOB_SECRET_ACCESS_KEY }}"
